services:
  react:
    container_name: mszan-portfolio-prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.production
      args:
        - REACT_APP_EMAILJS_USERID=${REACT_APP_EMAILJS_USERID}
    command: serve -s out -l 3000
    ports:
      - 4050:3000