FROM node:lts-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ARG REACT_APP_EMAILJS_USERID
ENV REACT_APP_EMAILJS_USERID=$REACT_APP_EMAILJS_USERID

COPY package.json /app/

RUN yarn install --silent

COPY ./ /app/

CMD ["yarn", "dev"]