
name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  tests:
    name: Test locally
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          token: ${{ secrets.REPO_TOKEN }}

      - name: Docker container BUILD
        run: docker build -f Dockerfile.production -t mszan-portfolio-prod:1.0 . --build-arg REACT_APP_EMAILJS_USERID=foo

      - name: Docker container UP
        run: docker container run --name mszan-portfolio -d -p 4000:3000 mszan-portfolio-prod:1.0

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        env:
          PRODUCTION_VPS_APP_PORT: ${{ secrets.PRODUCTION_VPS_APP_PORT }}
          PRODUCTION_VPS_APP_EMAILJS_USERID: ${{ secrets.PRODUCTION_VPS_APP_EMAILJS_USERID }}
        with:
          host: ${{ secrets.PRODUCTION_VPS_HOST }}
          username: ${{ secrets.PRODUCTION_VPS_USERNAME }}
          key: ${{ secrets.PRODUCTION_VPS_KEY }}
          command_timeout: 30m
          envs: PRODUCTION_VPS_APP_PORT,PRODUCTION_VPS_APP_EMAILJS_USERID
          script: |
            cd mszan-portfolio
            git pull origin master
            docker stop mszan-portfolio
            docker system prune --force
            docker build -f Dockerfile.production -t mszan-portfolio-prod:1.0 . --build-arg REACT_APP_EMAILJS_USERID=$PRODUCTION_VPS_APP_EMAILJS_USERID
            docker container run --name mszan-portfolio -d -p $PRODUCTION_VPS_APP_PORT:3000 mszan-portfolio-prod:1.0
            